export const cuisineList = [
  "Cuci dan Setrika Baju",
  "Boneka",
  "Selimut dan Sarung Bantal",
  "Peralatan Ibadah",
  "Tas",
  "Cuci Ekspres",
  // "Desserts",
  // "French",
  // "Greek",
  // "Healthy",
  // "Indian",
  // "Italian",
  // "Japanese",
  // "Mexican",
  // "Noodles",
  // "Organic",
  // "Pasta",
  // "Pizza",
  // "Salads",
  // "Seafood",
  // "Spanish",
  // "Steak",
  // "Sushi",
  // "Tacos",
  // "Tapas",
  // "Vegan",
];
